# Makefile
.DEFAULT_GOAL := default
.PHONY: all apply aws.login clean default destroy generate help init lint logs \
				moonlight moonlight.pair nuke plan provision provision.clear-state \
				provision.restart rdp reboot secrets.json show-ip show-password \
				sunshine sunshine.wait ssh ssh.wait upload

# Specify default environment if none provided
ENV ?= vultr

# Load specific dotenv files based on precedence
-include .env
-include .env.$(ENV)
-include .env.local
-include .env.$(ENV).local

export AWS_CONFIG_FILE
export AWS_PROFILE
export AWS_SHARED_CREDENTIALS_FILE
export AWS_REGION
export EPHEMERAL_SUNSHINE_PASSWORD
export EPHEMERAL_WINDOWS_IP
export EPHEMERAL_WINDOWS_PASSWORD
export MY_IP
export SSH_PUBLIC_KEY_FILE
export VULTR_API_KEY

RESOLVE_WINDOWS_IP = IP=$${EPHEMERAL_WINDOWS_IP:-$$(terramate run --tags=vultr:services:windows -- terraform output -raw vultr_instance_main_ip)}; \
	if [ -z "$$IP" ]; then echo "Missing IP"; exit 1; fi

RESOLVE_WINDOWS_PASSWORD = PW=$${EPHEMERAL_WINDOWS_PASSWORD:-$$(terramate run --tags=vultr:services:windows -- terraform output -raw vultr_instance_default_password)}; \
	if [ -z "$$PW" ]; then echo "Missing password"; exit 1; fi

all: init apply ssh.wait provision sunshine.wait moonlight.pair moonlight ## Does everything you need. Inits terraform stack, apply infra and provision once reachable, and then pairs sunshine with moonlight

apply: generate ## Applies terraform configuration to all stacks
	terramate run --tags=$(ENV) -- terraform apply -auto-approve

aws.login: ## Refresh AWS CLI login session for the selected profile
	aws login --profile $(AWS_PROFILE)

clean: ## Removes all temporary files generated by terramate and terraform
	find stacks -name ".terraform" -type d -prune -exec rm -rf {} \;

	find stacks -name ".terraform.lock.hcl" -type f -exec rm -f {} \;	
	find stacks -name "z_*.tf" -type f -exec rm -f {} \;	

	rm -rf .terraform-cache-dir/data/*
	rm -rf .terraform-cache-dir/plugins/*
	rm -rf .terraform-cache-dir/state/*

default: help  ## Shows help

destroy: generate ## Destroys all stacks (delete everything)
	terramate run --tags=$(ENV) --reverse -- terraform destroy -auto-approve

generate: ## Generates terraform configuration from terramate configuration files
	terramate generate

help: ## Show this help message.
	@echo 'Ephemeral Game infrastructure tool'
	@echo
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m\033[0m\n"} /^[$$()% a-zA-Z_.-]+:.*?##/ { printf "  \033[36m%-23s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

init: generate ## Inits environment
	terramate run --tags=$(ENV) -- terraform init -upgrade

lint:
	terramate fmt

logs: ## Fetch and print all provisioning logs from the Windows instance
	@$(RESOLVE_WINDOWS_IP); \
	SSH_OPTS='-o StrictHostKeyChecking=no -o ServerAliveInterval=10 -o WarnWeakCrypto=no-pq-kex -i $(SSH_PUBLIC_KEY_FILE)'; \
	printf '%s\n' "Fetching logs from $$IP..."; \
	ssh $$SSH_OPTS Administrator@$$IP "if (Test-Path 'C:\Users\Administrator\provision\scripts\logs.ps1') { & 'C:\Users\Administrator\provision\scripts\logs.ps1' } else { Write-Output 'No logs script found. Run make provision first.' }"

moonlight: sunshine.wait ## Start Moonlight
	@$(RESOLVE_WINDOWS_IP); \
	/Applications/Moonlight.app/Contents/MacOS/Moonlight stream --game-optimization $$IP "Desktop"

moonlight.pair: sunshine.wait ## Pair Moonlight with Sunshine using a fixed PIN while Moonlight is actively pairing
	@$(RESOLVE_WINDOWS_IP); \
	PIN=1234; \
	PAIR_RESPONSE_FILE=./tmp/moonlight-pair-response.json; \
	mkdir -p ./tmp; \
	rm -f $$PAIR_RESPONSE_FILE; \
	printf '%s\n' "Starting Moonlight pairing against $$IP with PIN $$PIN..."; \
	/Applications/Moonlight.app/Contents/MacOS/Moonlight pair --pin $$PIN $$IP & \
	MOONLIGHT_PID=$$!; \
	sleep 2; \
	printf '%s\n' "Submitting pairing PIN to Sunshine..."; \
	HTTP_CODE=$$(curl -sS -i -k \
	  -u "sunshine:$(EPHEMERAL_SUNSHINE_PASSWORD)" \
	  -H "Content-Type: application/json" \
	  --data-binary "{\"pin\":\"$$PIN\",\"name\":\"ephemeral-client\"}" \
	  -o $$PAIR_RESPONSE_FILE \
	  -w "%{http_code}" \
	  "https://$$IP:47990/api/pin"); \
	CURL_EXIT=$$?; \
	if [ $$CURL_EXIT -ne 0 ]; then \
	  kill $$MOONLIGHT_PID >/dev/null 2>&1 || true; \
	  wait $$MOONLIGHT_PID >/dev/null 2>&1 || true; \
	  echo "Sunshine pairing API call failed."; \
	  exit $$CURL_EXIT; \
	fi; \
	if ! printf '%s' "$$HTTP_CODE" | grep -q '^2'; then \
	  kill $$MOONLIGHT_PID >/dev/null 2>&1 || true; \
	  wait $$MOONLIGHT_PID >/dev/null 2>&1 || true; \
	  echo "Sunshine pairing API returned HTTP $$HTTP_CODE."; \
	  if [ -f $$PAIR_RESPONSE_FILE ]; then cat $$PAIR_RESPONSE_FILE; fi; \
	  exit 1; \
	fi; \
	printf '%s\n' "Sunshine pairing API accepted the PIN. Waiting for Moonlight to finish..."; \
	wait $$MOONLIGHT_PID

nuke: destroy clean ## Destroys all stacks and removes local terraform/terramate artifacts

plan: generate ## Plans terraform changes on all stacks
	terramate run --tags=$(ENV) -- terraform plan

provision: secrets.json upload ## Syncs provision scripts and runs bootstrap on remote host
	@$(RESOLVE_WINDOWS_IP); \
	SSH_OPTS='-o StrictHostKeyChecking=no -o ServerAliveInterval=10 -o WarnWeakCrypto=no-pq-kex -i $(SSH_PUBLIC_KEY_FILE)'; \
	ssh $$SSH_OPTS Administrator@$$IP 'New-Item -ItemType Directory -Force C:\Users\Administrator\provision | Out-Null; New-Item -ItemType Directory -Force C:\Users\Administrator\provision\state | Out-Null; if (Test-Path "C:\Users\Administrator\provision\scripts") { Remove-Item -Recurse -Force "C:\Users\Administrator\provision\scripts" }'; \
	scp $$SSH_OPTS -r windows/provision Administrator@$$IP:/C:/Users/Administrator/; \
	scp $$SSH_OPTS ./tmp/secrets.json Administrator@$$IP:/C:/Users/Administrator/provision/state/secrets.json; \
	ssh $$SSH_OPTS Administrator@$$IP '& "C:\Users\Administrator\provision\scripts\bootstrap.ps1"'

provision.clear-state: ## Clears remote provisioning state, logs, and downloads
	@$(RESOLVE_WINDOWS_IP); \
	SSH_OPTS='-o StrictHostKeyChecking=no -o ServerAliveInterval=10 -o WarnWeakCrypto=no-pq-kex -i $(SSH_PUBLIC_KEY_FILE)'; \
	ssh $$SSH_OPTS Administrator@$$IP 'if (Test-Path "C:\Users\Administrator\provision\state") { Remove-Item -Recurse -Force "C:\Users\Administrator\provision\state" }; if (Test-Path "C:\Users\Administrator\provision\logs") { Remove-Item -Recurse -Force "C:\Users\Administrator\provision\logs" }; if (Test-Path "C:\Users\Administrator\provision\downloads") { Remove-Item -Recurse -Force "C:\Users\Administrator\provision\downloads" }'

provision.restart: provision.clear-state provision ## Clears the provisioning state, uploads the new scripts and executes them

rdp: ## Writes ./tmp/windows.rdp and opens it for debugging
	@$(RESOLVE_WINDOWS_IP); \
	$(RESOLVE_WINDOWS_PASSWORD); \
	printf '%s\n' \
	  "full address:s:$$IP" \
	  "username:s:Administrator" \
	  "prompt for credentials on client:i:1" \
	  "administrative session:i:1" \
	  "screen mode id:i:2" \
	  "session bpp:i:32" \
	  "redirectclipboard:i:1" \
	  "audiomode:i:0" \
	  > ./tmp/windows.rdp; \
	printf '%s' "$$PW" | pbcopy; \
	open -a "Microsoft Remote Desktop" ./tmp/windows.rdp || open ./tmp/windows.rdp; \
	sleep 3; \
	osascript -e 'tell application "System Events" to keystroke "v" using command down' -e 'tell application "System Events" to key code 36'

reboot: ## Reboots the remote Windows instance
	@$(RESOLVE_WINDOWS_IP); \
	SSH_OPTS='-o StrictHostKeyChecking=no -o ServerAliveInterval=10 -o WarnWeakCrypto=no-pq-kex -i $(SSH_PUBLIC_KEY_FILE)'; \
	ssh $$SSH_OPTS Administrator@$$IP 'shutdown /r /t 0'

secrets.json: ## Writes ./tmp/secrets.json for Windows provisioning
	@$(RESOLVE_WINDOWS_PASSWORD); \
	jq -n \
	  --arg wp "$$PW" \
	  --arg sp "$(EPHEMERAL_SUNSHINE_PASSWORD)" \
	  '{windows_password: $$wp, sunshine_password: $$sp}' \
	  > ./tmp/secrets.json

show-ip: ## Displays instance public IP address
	@$(RESOLVE_WINDOWS_IP); \
	echo "$$IP"

show-password: ## Displays instance default password
	@$(RESOLVE_WINDOWS_PASSWORD); \
	echo "$$PW"

sunshine: ## Opens the Sunshine web UI in the local browser
	@$(RESOLVE_WINDOWS_IP); \
	open "https://$$IP:47990" || open -a "Google Chrome" "https://$$IP:47990"

sunshine.wait: ## Wait until Sunshine accepts authenticated API requests
	@$(RESOLVE_WINDOWS_IP); \
	ATTEMPT=1; \
	MAX_ATTEMPTS=20; \
	printf '%s\n' "Waiting for Sunshine API on $$IP:47990..."; \
	while [ $$ATTEMPT -le $$MAX_ATTEMPTS ]; do \
		HTTP_CODE=$$(curl -sS -k \
		  -u "sunshine:$(EPHEMERAL_SUNSHINE_PASSWORD)" \
		  -o /dev/null \
		  -w "%{http_code}" \
		  "https://$$IP:47990/api/config"); \
		CURL_EXIT=$$?; \
		if [ $$CURL_EXIT -eq 0 ] && printf '%s' "$$HTTP_CODE" | grep -q '^2'; then \
			printf '%s\n' "Sunshine API is ready on $$IP:47990"; \
			exit 0; \
		fi; \
		printf '%s\n' "Sunshine API not ready yet (attempt $$ATTEMPT/$$MAX_ATTEMPTS, curl=$$CURL_EXIT, http=$$HTTP_CODE). Sleeping 2 seconds..."; \
		sleep 2; \
		ATTEMPT=$$((ATTEMPT + 1)); \
	done; \
	printf '%s\n' "Sunshine API did not become ready in time."; \
	exit 1

ssh: ## Open an interactive SSH session to the Windows instance
	@$(RESOLVE_WINDOWS_IP); \
	SSH_OPTS='-o StrictHostKeyChecking=no -o ServerAliveInterval=10 -o WarnWeakCrypto=no-pq-kex -i $(SSH_PUBLIC_KEY_FILE)'; \
	ssh $$SSH_OPTS Administrator@$$IP

ssh.wait: ## Wait until SSH on the Windows host is reachable
	@$(RESOLVE_WINDOWS_IP); \
	SSH_OPTS='-o StrictHostKeyChecking=no -o ConnectTimeout=5 -o ServerAliveInterval=10 -o WarnWeakCrypto=no-pq-kex -i $(SSH_PUBLIC_KEY_FILE)'; \
	echo "Waiting for SSH on $$IP..."; \
	until ssh $$SSH_OPTS Administrator@$$IP exit 0 >/dev/null 2>&1; do \
		sleep 5; \
	done; \
	echo "SSH is ready on $$IP"

upload: ## Upload local non-committed files from ./upload, skipping files that already exist remotely
	@$(RESOLVE_WINDOWS_IP); \
	SSH_OPTS='-o StrictHostKeyChecking=no -o ServerAliveInterval=10 -o WarnWeakCrypto=no-pq-kex -i $(SSH_PUBLIC_KEY_FILE)'; \
	REMOTE_UPLOAD_DIR='C:\Users\Administrator\upload'; \
	REMOTE_DESKTOP_DIR='C:\Users\Administrator\Desktop\upload'; \
	printf '%s\n' "Preparing remote upload folder on $$IP..."; \
	ssh $$SSH_OPTS Administrator@$$IP "New-Item -ItemType Directory -Force '$$REMOTE_UPLOAD_DIR' | Out-Null; if (!(Test-Path '$$REMOTE_DESKTOP_DIR')) { cmd /c mklink /J \"$$REMOTE_DESKTOP_DIR\" \"$$REMOTE_UPLOAD_DIR\" >nul 2>&1 }"; \
	if [ ! -d ./upload ]; then \
		printf '%s\n' "No ./upload directory found. Skipping upload."; \
		exit 0; \
	fi; \
	find ./upload -type f ! -name '.gitkeep' -exec sh -c '\
		FILE="$$1"; \
		REL_PATH="$${FILE#./upload/}"; \
		REL_PATH_WIN=$$(printf "%s" "$$REL_PATH" | sed "s#/#\\\\\\\\#g"); \
		REL_DIR=$$(dirname "$$REL_PATH"); \
		if [ "$$REL_DIR" = "." ]; then \
			REMOTE_DIR="C:\\Users\\Administrator\\upload"; \
		else \
			REL_DIR_WIN=$$(printf "%s" "$$REL_DIR" | sed "s#/#\\\\\\\\#g"); \
			REMOTE_DIR="C:\\Users\\Administrator\\upload\\$$REL_DIR_WIN"; \
		fi; \
		ssh '"$$SSH_OPTS"' Administrator@'"$$IP"' "New-Item -ItemType Directory -Force '\''$$REMOTE_DIR'\'' | Out-Null"; \
		if ssh '"$$SSH_OPTS"' Administrator@'"$$IP"' "if (Test-Path '\''C:\\Users\\Administrator\\upload\\$$REL_PATH_WIN'\'') { exit 0 } else { exit 1 }" >/dev/null 2>&1; then \
			printf "%s\n" "Skipping existing upload file: $$REL_PATH"; \
		else \
			printf "%s\n" "Uploading: $$REL_PATH"; \
			scp '"$$SSH_OPTS"' "$$FILE" Administrator@'"$$IP"':/C:/Users/Administrator/upload/"$$REL_PATH"; \
		fi \
	' sh {} \;
