# Makefile

# Specify default environment if none provided
ENV ?= vultr

# Load specific dotenv files based on precedence
-include .env
-include .env.$(ENV)
-include .env.$(ENV).local

export AWS_CONFIG_FILE
export AWS_PROFILE
export AWS_SHARED_CREDENTIALS_FILE
export AWS_REGION
export EPHEMERAL_SUNSHINE_PASSWORD
export EPHEMERAL_WINDOWS_IP
export EPHEMERAL_WINDOWS_PASSWORD

default: help

help: ## Show this help message.
	@echo 'Ephemeral Game infrastructure tool'
	@echo
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m\033[0m\n"} /^[$$()% a-zA-Z_.-]+:.*?##/ { printf "  \033[36m%-23s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

aws.login: ## Refresh AWS CLI login session for the selected profile
	aws login --profile $(AWS_PROFILE)

apply: generate ## Applies terraform configuration to all stacks
	terramate run -- terraform apply -auto-approve

clean: ## Removes all temporary files generated by terramate and terraform
	find stacks -name ".terraform" -type d -prune -exec rm -rf {} \;

	find stacks -name ".terraform.lock.hcl" -type f -exec rm -f {} \;	
	find stacks -name "z_*.tf" -type f -exec rm -f {} \;	

	rm -rf .terraform-cache-dir/data/*
	rm -rf .terraform-cache-dir/plugins/*
	rm -rf .terraform-cache-dir/state/*

destroy: generate ## Destroys all stacks (delete everything)
	terramate run --reverse -- terraform destroy -auto-approve

generate: ## Generates terraform configuration from terramate configuration files
	terramate generate

init: generate ## Inits environment
	terramate run -- terraform init -upgrade

lint:
	terramate fmt

nuke: destroy clean ## Destroys all stacks and removes local terraform/terramate artifacts

plan: generate ## Plans terraform changes on all stacks
	terramate run -- terraform plan

provision: ## Syncs provision scripts and runs bootstrap on remote host
	ssh vultr 'New-Item -ItemType Directory -Force C:\Users\Administrator\provision | Out-Null; if (Test-Path "C:\Users\Administrator\provision\scripts") { Remove-Item -Recurse -Force "C:\Users\Administrator\provision\scripts" }'
	scp -r windows/provision vultr:/C:/Users/Administrator/
	ssh vultr '$$winPw = [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("$(shell printf %s "$(EPHEMERAL_WINDOWS_PASSWORD)" | base64)")); $$env:EPHEMERAL_WINDOWS_PASSWORD = $$winPw; $$sunPw = [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("$(shell printf %s "$(EPHEMERAL_SUNSHINE_PASSWORD)" | base64)")); $$env:EPHEMERAL_SUNSHINE_PASSWORD = $$sunPw; & "C:\Users\Administrator\provision\scripts\bootstrap.ps1"'

provision.clear-state: ## Clears remote provisioning state, logs, and downloads
	ssh vultr 'if (Test-Path "C:\Users\Administrator\provision\state") { Remove-Item -Recurse -Force "C:\Users\Administrator\provision\state" }; if (Test-Path "C:\Users\Administrator\provision\logs") { Remove-Item -Recurse -Force "C:\Users\Administrator\provision\logs" }; if (Test-Path "C:\Users\Administrator\provision\downloads") { Remove-Item -Recurse -Force "C:\Users\Administrator\provision\downloads" }'
