# Makefile

export AWS_CONFIG_FILE
export AWS_PROFILE
export AWS_SHARED_CREDENTIALS_FILE

default: help

help: ## Show this help message.
	@echo 'Ephemeral Game infrastructure tool'
	@echo
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m\033[0m\n"} /^[$$()% a-zA-Z_.-]+:.*?##/ { printf "  \033[36m%-23s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

apply: generate ## Applies terraform configuration to all stacks
	terramate run -- terraform apply -auto-approve

clean: ## Removes all temporary files generated by terramate and terraform
	find stacks -name ".terraform" -type d -prune -exec rm -rf {} \;

	find stacks -name ".terraform.lock.hcl" -type f -exec rm -f {} \;	
	find stacks -name "z_*.tf" -type f -exec rm -f {} \;	

	rm -rf .terraform-cache-dir/data/*
	rm -rf .terraform-cache-dir/plugins/*
	rm -rf .terraform-cache-dir/state/*

destroy: generate ## Destroys all stacks (delete everything)
	terramate run -- terraform destroy -auto-approve

generate: ## Generates terraform configuration from terramate configuration files
	terramate generate

init: generate ## Inits dev environment only
	terramate run -- terraform init -upgrade

lint:
	terramate fmt

nuke: destroy clean ## Destroys all stacks and removes local terraform/terramate artifacts

plan: generate ## Plans terraform changes on all stacks
	terramate run -- terraform plan
