#!/usr/bin/env ruby
# frozen_string_literal: true

instance = ENV["EGAME_INSTANCE_NAME"] || ARGV.first
unless instance && !instance.empty?
  warn "Usage: commands/up <instance>"
  exit 2
end

warn "[up] instance=#{instance} uses metal hardware; nothing to create."
